window.ROCK_PRODUCTS = [
  {id:'rkch720',name:'ROCK Power Charger',model:'RKCH720',category:'power',price:15,image:'assets/products/rkch720.webp'},
  {id:'rkch735',name:'ROCK Power Charger',model:'RKCH735',category:'power',price:20,image:'assets/products/rkch735.webp'},
  {id:'rkch765',name:'ROCK Fast Charger',model:'RKCH765',category:'power',price:40,image:'assets/products/rkch765.webp'},
  {id:'car30',name:'ROCK Car Charger',model:'C43',category:'car',price:46,image:'assets/products/car30.webp'},
  {id:'sd017',name:'ROCK Car Charger',model:'SD-017',category:'car',price:40,image:'assets/products/sd017.webp'},
  {id:'nc20',name:'ROCK NC-20 Audio Accessory',model:'NC-20',category:'audio',price:12,image:'assets/products/nc20.webp'},
  {id:'pods700',name:'ROCK Pods 700W',model:'RO-700W',category:'audio',price:79,image:'assets/products/pods700.webp'},
  {id:'eb200',name:'ROCK EB Wireless Earphones',model:'RAU0785',category:'audio',price:59,image:'assets/products/eb200.webp'},
  {id:'eb710',name:'ROCK EB Wireless Earphones',model:'RAU0788',category:'audio',price:44,image:'assets/products/eb710.webp'},
  {id:'s1',name:'ROCK S1 Wireless Accessory',model:'RAU0790',category:'audio',price:50,image:'assets/products/s1.webp'},
  {id:'a5pro',name:'ROCK A5 Pro',model:'RAU0782',category:'audio',price:65,image:'assets/products/a5pro.webp'},
  {id:'ro0546t',name:'ROCK Wired Earphone',model:'RO-0546T',category:'audio',price:14,image:'assets/products/ro0546t.webp'},
  {id:'aux139',name:'ROCK AUX-139',model:'AUX-139',category:'audio',price:7,image:'assets/products/aux139.webp'},
  {id:'y6',name:'ROCK Y6',model:'RAU0768',category:'audio',price:39,image:'assets/products/y6.webp'},
  {id:'es09',name:'ROCK ES09',model:'RAU0791',category:'audio',price:12,image:'assets/products/es09.webp'},
  {id:'rph1003',name:'ROCK RPH1003',model:'RPH1003',category:'audio',price:20,image:'assets/products/rph1003.webp'},
  {id:'rph0878',name:'ROCK RPH0878',model:'RPH0878',category:'audio',price:48,image:'assets/products/rph0878.webp'},
  {id:'ram0037',name:'ROCK Car Mount',model:'RAM0037',category:'car',price:28,image:'assets/products/ram0037.webp'},
  {id:'w31',name:'ROCK Wireless Charger',model:'118A-15W',category:'power',price:15,image:'assets/products/w31.webp'},
  {id:'pen',name:'ROCK Smart Pen',model:'RST10860',category:'lifestyle',price:39,image:'assets/products/pen.webp'},
  {id:'laptop-bag',name:'ROCK Laptop Bag',model:'RST10887',category:'lifestyle',price:28,image:'assets/products/laptop-bag.webp'},
  {id:'trimmer',name:'ROCK Trimmer',model:'RST10890',category:'lifestyle',price:40,image:'assets/products/trimmer.webp'},
  {id:'rkcb146',name:'ROCK Fast Charging Cable USB-A to Lightning 27W - 1.0M',model:'RKCBL146',category:'power',price:6.25,image:'assets/products/catalog-placeholder.svg'},
  {id:'rkcb144',name:'ROCK Fast Charging Cable USB-C to Lightning 27W - 1.0M',model:'RKCBL144',category:'power',price:6.25,image:'assets/products/c27l.webp'},
  {id:'rkcb148',name:'ROCK Fast Charging Cable USB-A to USB-C 60W - 1.0M',model:'RKCBL148',category:'power',price:6.25,image:'assets/products/a60c.webp'},
  {id:'rkcb147',name:'ROCK Fast Charging Cable USB-C to USB-C 60W - 1.0M',model:'RKCBL147',category:'power',price:6.25,image:'assets/products/cc60.webp'},
  {id:'rkcb145',name:'ROCK Fast Charging Cable USB-A to Micro 12W - 1.0M',model:'RKCBL145',category:'power',price:6.25,image:'assets/products/a12m.webp'},
  {id:'rcb056',name:'ROCK Fast Charging Cable USB-A with Multi Connector - 120cm',model:'RCB056',category:'power',price:6.25,image:'assets/products/metal3in1.webp'},
  {id:'ro701w',name:'ROCK Pods 701 Bluetooth Earphones - White',model:'RO-701W',category:'audio',price:69,image:'assets/products/catalog-placeholder.svg'},
  {id:'rau0785b',name:'ROCK EB TWS AI Smart Earphones - Black',model:'RAU0785',category:'audio',price:59,image:'assets/products/eb200.webp'},
  {id:'hp6030-silver',name:'ROCK 05 Wireless Headphones - Silver',model:'HP-6030BT',category:'audio',price:46,image:'assets/products/catalog-placeholder.svg'},
  {id:'hp6030-grey',name:'ROCK 05 Wireless Headphones - Grey',model:'HP-6030BT',category:'audio',price:46,image:'assets/products/catalog-placeholder.svg'},
  {id:'ro0545',name:'ROCK Wired Earphone iPhone Lateral In-Ear - White',model:'RO-0545',category:'audio',price:15,image:'assets/products/catalog-placeholder.svg'},
  {id:'rocktag-beige',name:'ROCK Tag Wireless Smart Tracker - Beige',model:'ROCK Tag',category:'lifestyle',price:20,image:'assets/products/catalog-placeholder.svg'},
  {id:'rocktag-black',name:'ROCK Tag Wireless Smart Tracker - Black',model:'ROCK Tag',category:'lifestyle',price:20,image:'assets/products/catalog-placeholder.svg'},
  {id:'barcode-6822154851697',name:'ROCK 120W Dual-Ended Retractable Cable USB + Type-C',model:'-',category:'power',price:13,image:'assets/products/catalog-placeholder.svg'},
  {id:'barcode-6815213515838',name:'ROCK 68W Car Charger 2 Type-C + USB PD/QC',model:'-',category:'car',price:28,image:'assets/products/catalog-placeholder.svg'},
  {id:'barcode-6815213515821',name:'ROCK 50W GaN Wall Charger USB + Type-C',model:'-',category:'power',price:37,image:'assets/products/catalog-placeholder.svg'},
  {id:'barcode-6815213515845',name:'ROCK 45W Car Charger USB + Type-C Dual Cable',model:'-',category:'car',price:36,image:'assets/products/catalog-placeholder.svg'},
  {id:'barcode-6815213515814',name:'ROCK Wired Type-C Headphones 120cm',model:'-',category:'audio',price:19,image:'assets/products/catalog-placeholder.svg'},
  {id:'barcode-6658741587843',name:'ROCK 45W GaN Wall Charger Type-C PD',model:'-',category:'power',price:25,image:'assets/products/catalog-placeholder.svg'}
];
