const nav=document.getElementById('nav'),menuBtn=document.getElementById('menuBtn'),mobileMenu=document.getElementById('mobileMenu'),cartBtn=document.getElementById('cartBtn'),closeCart=document.getElementById('closeCart'),cartDrawer=document.getElementById('cartDrawer'),overlay=document.getElementById('overlay'),cartItems=document.getElementById('cartItems'),cartCount=document.getElementById('cartCount'),cartTotal=document.getElementById('cartTotal'),langBtn=document.getElementById('langBtn');
document.getElementById('year').textContent=new Date().getFullYear();
const products=[
{name:'ROCK GaN 65W',category:'power',label:'CHARGER',desc:'شاحن سريع صغير بتقنية GaN ومناسب للاستخدام اليومي.',price:129,art:'charger-art',badge:'BEST SELLER'},
{name:'ROCK Power 20K',category:'power',label:'POWER BANK',desc:'بطارية متنقلة 20,000mAh مع طاقة تصل إلى 22.5W.',price:149,art:'power-art',badge:'FEATURED'},
{name:'ROCK USB-C 100W',category:'power',label:'CABLE',desc:'كيبل USB-C عملي للشحن السريع ونقل الطاقة.',price:59,art:'cable-art',badge:'NEW'},
{name:'ROCK MagSafe Case',category:'protection',label:'PROTECTION',desc:'حماية خفيفة بتصميم نظيف وتوافق مغناطيسي.',price:89,art:'case-art',badge:'POPULAR'},
{name:'ROCK Glass Pro',category:'protection',label:'SCREEN',desc:'حماية شاشة واضحة مع تركيب سهل للاستخدام اليومي.',price:49,art:'case-art',badge:'NEW'},
{name:'ROCK AirBuds',category:'audio',label:'AUDIO',desc:'سماعات لاسلكية بتصميم مريح وصوت واضح.',price:179,art:'earbuds-art',badge:'BEST SELLER'},
{name:'ROCK Sound Mini',category:'audio',label:'AUDIO',desc:'سماعة صغيرة للحياة اليومية والتنقل.',price:119,art:'earbuds-art',badge:'POPULAR'},
{name:'ROCK 3-in-1 Cable',category:'power',label:'CABLE',desc:'كيبل متعدد الاستخدامات للشحن في أكثر من سيناريو.',price:69,art:'cable-art',badge:'SMART PICK'}
];
let activeFilter='all',query='',cart=[];
const grid=document.getElementById('productGrid'),empty=document.getElementById('emptyProducts'),search=document.getElementById('productSearch'),sort=document.getElementById('sortProducts');
function productList(){let list=products.filter(p=>(activeFilter==='all'||p.category===activeFilter)&&(`${p.name} ${p.label} ${p.desc}`.toLowerCase().includes(query.toLowerCase())));if(sort.value==='price-low')list.sort((a,b)=>a.price-b.price);if(sort.value==='price-high')list.sort((a,b)=>b.price-a.price);if(sort.value==='name')list.sort((a,b)=>a.name.localeCompare(b.name));return list}
function renderProducts(){const list=productList();empty.style.display=list.length?'none':'block';grid.innerHTML=list.map((p,i)=>`<article class="product-card reveal visible"><div class="product-visual"><span class="product-badge">${p.badge}</span><div class="product-art ${p.art}"></div></div><div class="product-info"><span class="product-category">${p.label}</span><h3>${p.name}</h3><p>${p.desc}</p><div class="product-bottom"><strong class="product-price">${p.price} ر.س</strong><button class="product-add" data-product="${p.name}" data-price="${p.price}" aria-label="إضافة ${p.name}">+</button></div></div></article>`).join('');grid.querySelectorAll('.product-add').forEach(b=>b.addEventListener('click',()=>addToCart(b.dataset.product,Number(b.dataset.price))));}
function addToCart(name,price){cart.push({name,price});renderCart();openCart()}
function renderCart(){if(!cart.length){cartItems.innerHTML='<div class="empty-cart">السلة فارغة<br><span>أضف منتجًا لتبدأ</span></div>';cartCount.textContent='0';cartTotal.textContent='0 ر.س';return}cartItems.innerHTML=cart.map((p,i)=>`<div class="cart-row"><div><strong>${p.name}</strong><small>${p.price} ر.س</small></div><button class="cart-remove" data-index="${i}">إزالة</button></div>`).join('');cartCount.textContent=cart.length;cartTotal.textContent=`${cart.reduce((s,p)=>s+p.price,0)} ر.س`;cartItems.querySelectorAll('.cart-remove').forEach(b=>b.addEventListener('click',()=>{cart.splice(+b.dataset.index,1);renderCart()}))}
function openCart(){cartDrawer.classList.add('open');overlay.classList.add('open');document.body.classList.add('no-scroll')}
function hideCart(){cartDrawer.classList.remove('open');overlay.classList.remove('open');document.body.classList.remove('no-scroll')}
function setFilter(filter){activeFilter=filter;document.querySelectorAll('#filterPills button').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));renderProducts()}
menuBtn?.addEventListener('click',()=>mobileMenu.classList.toggle('open'));mobileMenu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>mobileMenu.classList.remove('open')));cartBtn?.addEventListener('click',openCart);closeCart?.addEventListener('click',hideCart);overlay?.addEventListener('click',hideCart);
document.querySelectorAll('.add-demo').forEach(btn=>btn.addEventListener('click',()=>addToCart(btn.dataset.product,Number(btn.dataset.price))));
document.querySelectorAll('#filterPills button').forEach(btn=>btn.addEventListener('click',()=>setFilter(btn.dataset.filter)));
document.querySelectorAll('[data-filter-link]').forEach(card=>card.addEventListener('click',()=>setFilter(card.dataset.filterLink)));
search?.addEventListener('input',e=>{query=e.target.value;renderProducts()});sort?.addEventListener('change',renderProducts);
document.getElementById('filterToggle')?.addEventListener('click',()=>document.getElementById('filterPills').classList.toggle('open'));
window.addEventListener('scroll',()=>nav.classList.toggle('scrolled',window.scrollY>30));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
window.addEventListener('mousemove',e=>{document.querySelectorAll('.parallax').forEach(el=>{const r=el.getBoundingClientRect();const x=(e.clientX-(r.left+r.width/2))*0.015;const y=(e.clientY-(r.top+r.height/2))*0.01;el.style.transform=`translate(${x}px,${y}px)`})});
const searchOverlay=document.getElementById('searchOverlay'),searchBtn=document.getElementById('searchBtn'),closeSearch=document.getElementById('closeSearch'),overlaySearch=document.getElementById('overlaySearch');
searchBtn?.addEventListener('click',()=>{searchOverlay.classList.add('open');overlaySearch.focus()});closeSearch?.addEventListener('click',()=>searchOverlay.classList.remove('open'));overlaySearch?.addEventListener('input',e=>{query=e.target.value;search.value=e.target.value;renderProducts()});
let english=false;langBtn?.addEventListener('click',()=>{english=!english;document.documentElement.dir=english?'ltr':'rtl';document.documentElement.lang=english?'en':'ar';langBtn.textContent=english?'AR':'EN';document.querySelector('.hero h1').innerHTML=english?'Tech<br><em>that moves</em> with you':'تقنية<br><em>تتحرك</em> معك';document.querySelector('.hero-text').textContent=english?'Mobile accessories built around performance, design and reliability — from the first charge to the last moment of your day.':'إكسسوارات جوال تجمع بين الأداء، التصميم والاعتمادية — من أول شحنة إلى آخر لحظة في يومك.'});
document.getElementById('checkoutBtn')?.addEventListener('click',()=>alert('سلة ROCK جاهزة — اربط زر إتمام الطلب ببوابة الدفع أو واتساب عند تجهيز المتجر للبيع.'));
renderProducts();renderCart();