const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const nav=$('#nav'),menuBtn=$('#menuBtn'),mobileMenu=$('#mobileMenu'),cartBtn=$('#cartBtn'),closeCart=$('#closeCart'),cartDrawer=$('#cartDrawer'),overlay=$('#overlay'),cartItems=$('#cartItems'),cartCount=$('#cartCount'),cartTotal=$('#cartTotal'),langBtn=$('#langBtn');
const grid=$('#productGrid'),empty=$('#emptyProducts'),search=$('#productSearch'),sort=$('#sortProducts');
$('#year').textContent=new Date().getFullYear();
const products=[
{id:'eb200',name:'ROCK EB200 TWS Smart Earphones',category:'audio',label:'WIRELESS EARPHONES',desc:'سماعات TWS ذكية مع صوت اتجاهي، ENC وعمر بطارية طويل.',price:null,art:'earbuds-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['التنقل','المكالمات'],specs:[['Bluetooth','5.4'],['السعة','40mAh + 400mAh'],['البطارية','حتى 20 ساعة']]},
{id:'s1',name:'ROCK S1 Smart Touch Screen TWS Earphones',category:'audio',label:'WIRELESS EARPHONES',desc:'سماعات TWS بشاشة لمس ملونة وتحكم ذكي وتصميم In-Ear.',price:null,art:'earbuds-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['الاستخدام اليومي','التنقل'],specs:[['Bluetooth','5.4'],['الشاشة','LCD Full-Color Touchscreen'],['البطارية','16H']]},
{id:'eb710',name:'ROCK EB710 Bluetooth Earphones',category:'audio',label:'WIRELESS EARPHONES',desc:'سماعات In-Ear مريحة مع محركات 13mm وصوت ستيريو ثنائي القنوات.',price:null,art:'earbuds-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['المكالمات','الموسيقى'],specs:[['Bluetooth','5.3'],['Driver','13mm Dynamic'],['البطارية','حوالي 18 ساعة']]},
{id:'eb500',name:'ROCK EB500 Sound Earcuffs OWS',category:'audio',label:'WIRELESS EARPHONES',desc:'سماعات مفتوحة مريحة مع OWS وENC وصوت بانورامي.',price:null,art:'earbuds-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['الرياضة','الاستخدام اليومي'],specs:[['Bluetooth','5.4'],['Battery','24H'],['Charging Case','400mAh']]},
{id:'x718',name:'ROCK X718 OWS Bluetooth Earphones',category:'audio',label:'WIRELESS EARPHONES',desc:'سماعات OWS مريحة مع OWS وENC وصوت بانورامي واتصال منخفض التأخير.',price:null,art:'earbuds-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['الرياضة','المكالمات'],specs:[['Bluetooth','5.4'],['Battery','حتى 30 ساعة'],['Case','400mAh']]},
{id:'eb600',name:'ROCK EB600 TWS Bluetooth Earphones',category:'audio',label:'WIRELESS EARPHONES',desc:'سماعات TWS بصوت Hi-Fi وإلغاء ضوضاء للمكالمات وتصميم مريح.',price:null,art:'earbuds-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['الموسيقى','المكالمات'],specs:[['Bluetooth','5.4'],['Case','230mAh'],['Earbuds','30mAh']]},
{id:'retro-tws',name:'ROCK Retro Style TWS Earphones',category:'audio',label:'WIRELESS EARPHONES',desc:'سماعات TWS بطابع Retro خفيف ومضغوط مع مزامنة صوتية منخفضة التأخير.',price:null,art:'earbuds-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['التنقل','الاستخدام اليومي'],specs:[['Bluetooth','5.3'],['Design','Retro'],['Use','Portable']]},
{id:'a5pro',name:'ROCK A5 Pro Smart Touch Screen ANC TWS',category:'audio',label:'WIRELESS EARPHONES',desc:'سماعات TWS بشاشة لمس وإلغاء ضوضاء نشط وجودة صوت Hi-Fi.',price:null,art:'earbuds-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['المكالمات','التنقل'],specs:[['ANC','Active Noise Cancellation'],['Screen','LCD Full Color'],['Sound','Hi-Fi Lossless']]},
{id:'eb800',name:'ROCK EB800 Noise-Cancelling TWS Earphones',category:'audio',label:'WIRELESS EARPHONES',desc:'سماعات TWS مع إلغاء ضوضاء مزدوج، مقاومة ضغط وآداء صوت عالي الوضوح.',price:null,art:'earbuds-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['العمل','التنقل'],specs:[['Noise Control','حتى 32dB'],['Battery','16H'],['Fit','Zero-Pressure']]},
{id:'ultra-ow',name:'ROCK Sound Earcuffs ULTRA OWS',category:'audio',label:'WIRELESS EARPHONES',desc:'سماعات مفتوحة بتجربة صوتية ثلاثية الأبعاد وGyroscope وENC.',price:null,art:'earbuds-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['الرياضة','الموسيقى'],specs:[['Bluetooth','5.4'],['Battery','350mAh case'],['Type','OWS']]},
{id:'pro-ow',name:'ROCK Sound Earcuffs Pro OWS',category:'audio',label:'WIRELESS EARPHONES',desc:'سماعات OWS Pro بصوت ستيريو غامر، OWS وENC واقتران فوري.',price:null,art:'earbuds-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['الرياضة','التنقل'],specs:[['Bluetooth','5.4'],['Battery','350mAh case'],['Feature','Instant Pairing']]},
{id:'retro-mix',name:'ROCK Retro Mix Tape TWS Earphones',category:'audio',label:'WIRELESS EARPHONES',desc:'سماعات TWS بطابع شريط كاسيت Retro وتصميم مدمج مقاوم للماء.',price:null,art:'earbuds-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['السفر','الموسيقى'],specs:[['Bluetooth','5.3'],['Protection','IPX4'],['Playback','حوالي 4 ساعات']]},
{id:'eb700',name:'ROCK EB700 TWS Bluetooth Earphones',category:'audio',label:'WIRELESS EARPHONES',desc:'سماعات TWS مع تجربة Hi-Fi وتحكم لمس وبطارية طويلة.',price:null,art:'earbuds-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['الألعاب','المكالمات'],specs:[['Bluetooth','5.3'],['Driver','Composite Diaphragm'],['Battery','25mAh + 250mAh']]},
{id:'eb900',name:'ROCK EB900 TWS Bluetooth Earphones',category:'audio',label:'WIRELESS EARPHONES',desc:'سماعات TWS بعمر بطارية طويل وتحكم لمس ودون تأخير.',price:null,art:'earbuds-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['الاستخدام الطويل','العمل'],specs:[['Bluetooth','5.3'],['Battery','300mAh case'],['Battery Life','150H standby']]},
{id:'pods700',name:'ROCK Pods 700 Bluetooth Earphones',category:'audio',label:'WIRELESS EARPHONES',desc:'سماعات خفيفة مع عزل ضوضاء محيطية وشحن Lightning.',price:null,art:'earbuds-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['التنقل','المكالمات'],specs:[['Bluetooth','5.1'],['Case','400mAh'],['Music Time','3–4H']]},
{id:'hp85',name:'ROCK 85 Wireless Headphones',category:'audio',label:'HEADPHONES',desc:'سماعات رأس لاسلكية بوسائد مريحة وإلغاء صدى وعمر بطارية طويل.',price:null,art:'earbuds-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['المكتب','السفر'],specs:[['Bluetooth','5.3'],['Driver','40mm'],['Music','حتى 36H']]},
{id:'h2',name:'ROCK H2 Wireless Headphone',category:'audio',label:'HEADPHONES',desc:'سماعة رأس لاسلكية بصوت واضح وبطارية 400mAh وتصميم خفيف.',price:null,art:'earbuds-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['العمل','الترفيه'],specs:[['Bluetooth','5.0'],['Battery','400mAh'],['Playback','حوالي 15H']]},
{id:'h3',name:'ROCK H3 ANC Wireless Headphones',category:'audio',label:'HEADPHONES',desc:'سماعات رأس لاسلكية مع ANC، مكالمات واضحة وعمر بطارية طويل.',price:null,art:'earbuds-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['الطيران','المكتب'],specs:[['Bluetooth','5.2'],['Battery','400mAh'],['Music','حوالي 22H']]},
{id:'y6',name:'ROCK Y6 Neckband Wireless Sports Earphone',category:'audio',label:'SPORTS AUDIO',desc:'سماعة Neckband رياضية لاسلكية مع بطارية انتظار طويلة وشحن سريع.',price:null,art:'earbuds-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['الرياضة','التنقل'],specs:[['Bluetooth','5.3'],['Battery','165mAh'],['Standby','حوالي 100H']]},
{id:'es09',name:'ROCK ES09 Type-C Digital Wired Earphones',category:'audio',label:'WIRED EARPHONES',desc:'سماعات سلكية USB-C خفيفة مع ميكروفون HD ودرايفر 10mm.',price:null,art:'cable-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['المكتب','الجوال'],specs:[['Connector','Type-C'],['Driver','10mm'],['Cable','1.2m']]},
{id:'ro0546t',name:'ROCK RO-0546T Type-C Stereo Earphone',category:'audio',label:'WIRED EARPHONES',desc:'سماعات Type-C ستيريو خفيفة مع شريحة فك رقمي وتصميم مريح.',price:null,art:'cable-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['الجوال','المكالمات'],specs:[['Connector','Type-C'],['Cable','1200mm'],['Material','ABS+TPE']]},
{id:'aux139',name:'ROCK AUX-139 Stereo Earphone',category:'audio',label:'WIRED EARPHONES',desc:'سماعات نصف داخل الأذن مع صوت ستيريو وميكروفون وتحكم بالمكالمات.',price:null,art:'cable-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['الاستخدام اليومي','المكالمات'],specs:[['Cable','1200mm'],['Material','ABS+TPE'],['Design','Half-Ear']]},
{id:'rkch765',name:'ROCK RKCH765 65W GaN Charger',category:'power',label:'WALL CHARGER',desc:'شاحن GaN بقدرة 65W وثلاثة مخارج 2C+A للشحن المتزامن.',price:null,art:'charger-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['اللابتوب','السفر'],specs:[['Power','65W'],['Ports','2C + 1A'],['Input','100–240V']]},
{id:'rkch735',name:'ROCK RKCH735 35W GaN Charger',category:'power',label:'WALL CHARGER',desc:'شاحن مزدوج PD+QC بقدرة 35W بحجم صغير.',price:null,art:'charger-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['الجوال','السفر'],specs:[['Power','35W'],['Ports','USB + PD'],['Input','100–240V']]},
{id:'rkch720',name:'ROCK RKCH720 20W GaN Charger',category:'power',label:'WALL CHARGER',desc:'شاحن مزدوج PD+QC بقدرة 20W وتصميم مدمج.',price:null,art:'charger-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['الجوال','السفر'],specs:[['Power','20W'],['Ports','USB + PD'],['Input','100–240V']]},
{id:'retract70',name:'ROCK Retractable 70cm USB-C Cable',category:'power',label:'CABLE',desc:'كيبل قابل للسحب مدمج بطول 70cm مع تحكم حراري وتخزين مغناطيسي.',price:null,art:'cable-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['السيارة','السفر'],specs:[['Length','70cm'],['Connector','USB-C'],['Feature','Retractable']]},
{id:'wallpb10k',name:'ROCK 22.5W Wall Charger Power Bank 10000mAh',category:'power',label:'POWER BANK',desc:'باور بنك 10000mAh مع كيابل مدمجة وتصميم يجمع الشاحن والبطارية.',price:null,art:'power-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['السفر','الطوارئ'],specs:[['Capacity','10000mAh'],['Power','22.5W'],['Cables','Built-in Dual Cables']]},
{id:'p56',name:'ROCK P56 PD Fast Charging Power Bank',category:'power',label:'POWER BANK',desc:'باور بنك PD سريع مع كيبل قابل للسحب بسعة 10000mAh.',price:null,art:'power-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['السفر','الاستخدام الطويل'],specs:[['Capacity','10000mAh'],['Rated','9300mAh'],['Feature','Retractable Cable']]},
{id:'p28',name:'ROCK P28 Magnetic PD Fast Charging Power Bank',category:'power',label:'POWER BANK',desc:'باور بنك مغناطيسي بسعة 10000mAh وكيبل PD مدمج بقوة 20W.',price:null,art:'power-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['iPhone','السفر'],specs:[['Capacity','10000mAh'],['Power','PD 20W'],['Feature','Magnetic Alignment']]},
{id:'retro-mag10k',name:'ROCK PD20W Retro Magnetic Wireless Power Bank',category:'power',label:'POWER BANK',desc:'باور بنك مغناطيسي بتصميم Retro مع شحن سلكي ولاسلكي.',price:null,art:'power-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['iPhone','التنقل'],specs:[['Capacity','10000mAh'],['Power','PD 20W'],['Feature','Magnetic Wireless']]},
{id:'y18',name:'ROCK Y18 22.5W Fast Charging Power Bank',category:'power',label:'POWER BANK',desc:'باور بنك 20000mAh مع شاشة رقمية وكيبل قابل للسحب.',price:null,art:'power-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['السفر','الرحلات'],specs:[['Capacity','20000mAh'],['Power','22.5W'],['Display','Digital']]},
{id:'fridge20k',name:'ROCK Y18 Fridge Series 20K Power Bank',category:'power',label:'POWER BANK',desc:'باور بنك 20000mAh PD22.5W مع كيابل مدمجة وتصميم سفر.',price:null,art:'power-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['السفر','الاستخدام الطويل'],specs:[['Capacity','20000mAh'],['Power','22.5W'],['Feature','Built-in Cables']]},
{id:'gan30pb',name:'ROCK Portable Power Bank with GaN PD30W',category:'power',label:'POWER BANK',desc:'باور بنك محمول مع GaN PD30W وقابس AC قابل للطي وحماية متعددة.',price:null,art:'power-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['السفر','اللابتوب'],specs:[['Output','PD 30W'],['Form','Portable'],['Plug','Foldable AC']]},
{id:'powersack10k',name:'ROCK PowerStack Fast Charging Power Bank',category:'power',label:'POWER BANK',desc:'باور بنك 10000mAh مع كيبل شحن مدمج وتحكم حراري ذكي.',price:null,art:'power-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['السفر','الطوارئ'],specs:[['Capacity','10000mAh'],['Power','Fast Charging'],['Feature','Built-in Cable']]},
{id:'magholder10k',name:'ROCK Magnetic Holder Wireless Power Bank 10000mAh',category:'power',label:'POWER BANK',desc:'باور بنك مغناطيسي 10000mAh مع تثبيت مستقر وشحن سلكي ولاسلكي.',price:null,art:'power-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['iPhone','السيارة'],specs:[['Capacity','10000mAh'],['Charging','Magnetic + Wired'],['Protection','Trickle Protection']]},
{id:'travel10k',name:'ROCK Travel Series Power Bank 10000mAh',category:'power',label:'POWER BANK',desc:'باور بنك للسفر مع كيابل مدمجة ومخرج USB-A وشحن متعدد.',price:null,art:'power-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['السفر','الرحلات'],specs:[['Capacity','10000mAh'],['Output','USB-A 5V/2.4A'],['Series','Travel']]},
{id:'metal3in1',name:'ROCK 3-in-1 Metal Braided Charging Cable',category:'power',label:'CABLE',desc:'كيبل معدني مضفر 3-in-1 عالي التيار مع حماية Smart Chip.',price:null,art:'cable-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['السفر','السيارة'],specs:[['Length','120cm'],['Current','3.5A Max'],['Outputs','Lightning / Micro / Type-C']]},
{id:'cc60',name:'ROCK 60W USB-C to USB-C Cable',category:'power',label:'CABLE',desc:'كيبل USB-C إلى USB-C بقدرة 60W ونقل بيانات 480Mbps.',price:null,art:'cable-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['اللابتوب','الجوال'],specs:[['Power','60W'],['Length','100cm'],['Data','480Mbps']]},
{id:'c60l27',name:'ROCK 60W USB-C to Lightning Cable',category:'power',label:'CABLE',desc:'كيبل USB-C إلى Lightning مضفر للشحن السريع ونقل البيانات.',price:null,art:'cable-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['iPhone','iPad'],specs:[['Power','60W'],['Length','100cm'],['Material','Aluminum + Braided']]},
{id:'a60c',name:'ROCK 60W USB-A to Type-C Cable',category:'power',label:'CABLE',desc:'كيبل USB-A إلى Type-C بقدرة 60W وشحن سريع ونقل بيانات.',price:null,art:'cable-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['الجوال','الشحن اليومي'],specs:[['Power','60W'],['Length','100cm'],['Data','480Mbps']]},
{id:'a5c',name:'ROCK 5A USB-A to Type-C Cable',category:'power',label:'CABLE',desc:'كيبل USB-A إلى Type-C بتيار 5A للشحن السريع والفعّال.',price:null,art:'cable-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['iPhone','الشحن السريع'],specs:[['Current','5A'],['Length','100cm'],['Compatibility','Wide']]},
{id:'c27l',name:'ROCK 27W Type-C to Lightning Cable',category:'power',label:'CABLE',desc:'كيبل Type-C إلى Lightning بقدرة 27W مع نقل بيانات 480Mbps.',price:null,art:'cable-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['iPhone','الشحن السريع'],specs:[['Power','27W'],['Length','100cm'],['Data','480Mbps']]},
{id:'a12l',name:'ROCK 12W USB-A to Lightning Cable',category:'power',label:'CABLE',desc:'كيبل USB-A إلى Lightning بقدرة 12W وتصميم مضفر.',price:null,art:'cable-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['iPhone','الاستخدام اليومي'],specs:[['Power','12W'],['Length','100cm'],['Current','2.4A']]},
{id:'a12m',name:'ROCK 12W USB-A to Micro Cable',category:'power',label:'CABLE',desc:'كيبل USB-A إلى Micro بقدرة 12W وتصميم مضفر ومتين.',price:null,art:'cable-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['الأجهزة القديمة','الشحن اليومي'],specs:[['Power','12W'],['Length','100cm'],['Current','2.4A']]},
{id:'car30',name:'ROCK H30 Car Charger with Retractable Type-C Cable',category:'car',label:'CAR CHARGER',desc:'شاحن سيارة بكيبل Type-C قابل للسحب ومخرج A/C حتى 45W.',price:null,art:'charger-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['السيارة','السفر'],specs:[['Power','45W Total'],['Cable','Retractable Type-C'],['Voltage','12–24V']]},
{id:'b301',name:'ROCK B301 PD Bluetooth FM Transmitter',category:'car',label:'CAR CHARGER',desc:'مرسل FM بلوتوث مع منافذ USB ومكالمات بدون يد وملاحة صوتية.',price:null,art:'charger-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['السيارة','الرحلات'],specs:[['Bluetooth','5.0'],['USB','3 Ports'],['Feature','FM Transmitter']]},
{id:'sd017',name:'ROCK SD-017 H16 Dual Port A+C PD72W Car Charger',category:'car',label:'CAR CHARGER',desc:'شاحن سيارة مزدوج A+C بقدرة قصوى 72W مع شاشة جهد رقمية.',price:null,art:'charger-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['السيارة','الشحن السريع'],specs:[['Power','72W'],['Ports','USB-A + Type-C'],['Display','Real-Time Voltage']]},
{id:'nc20',name:'ROCK NC-20 H0 Dual Port A+C 15W Car Charger',category:'car',label:'CAR CHARGER',desc:'شاحن سيارة مزدوج A+C بقدرة 15W مع حماية وSmart Chip.',price:null,art:'charger-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['السيارة','الاستخدام اليومي'],specs:[['Power','15W'],['Ports','USB-A + Type-C'],['Material','Fireproof ABS+PC']]},
{id:'s5',name:'ROCK S5 Crystal Bluetooth Speaker with Light',category:'audio',label:'BLUETOOTH SPEAKER',desc:'سماعة بلوتوث شفافة مع إضاءة محيطية وصوت 52mm كامل المدى.',price:null,art:'speaker-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['المنزل','الحفلات'],specs:[['Bluetooth','5.1'],['Driver','52mm'],['Battery','4000mAh']]},
{id:'fabric-speaker',name:'ROCK Fabric Mesh Portable Bluetooth Speaker',category:'audio',label:'BLUETOOTH SPEAKER',desc:'سماعة محمولة بغطاء قماشي وصوت محيطي وتصميم مدمج.',price:null,art:'speaker-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['المنزل','السفر'],specs:[['Bluetooth','5.3'],['Battery','1200mAh'],['Playback','حوالي 3 ساعات']]},
{id:'rph1000',name:'ROCK RPH1000 Magnetic 360° Air Vent Car Mount',category:'holder',label:'HOLDER',desc:'حامل سيارة مغناطيسي قوي مع دوران حر وتصميم خطاف ثابت.',price:null,art:'case-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['السيارة','التنقل'],specs:[['Mount','Air Vent'],['Rotation','360°'],['Material','ABS+PC']]},
{id:'ram0037',name:'ROCK RAM0037 Q08 Magnetic Car Mount',category:'holder',label:'HOLDER',desc:'حامل سيارة مغناطيسي قابل للطي وتعديل الارتفاع مع تثبيت قوي.',price:null,art:'case-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['السيارة','السفر'],specs:[['Material','Zinc Alloy + POM'],['Type','Magnetic'],['Feature','Foldable / Adjustable']]},
{id:'w22',name:'ROCK W22 Car Mount with Infrared Sensor',category:'holder',label:'HOLDER',desc:'حامل سيارة بحساس أشعة تحت الحمراء وقفل تلقائي ودوران 360°.',price:null,art:'case-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['السيارة','التنقل'],specs:[['Input','Type-C 5V/2A'],['Rotation','360°'],['Lock','Infrared Auto Lock']]},
{id:'rph0876',name:'ROCK RPH0876 Universal Stretchable Car Headrest Mount',category:'holder',label:'HOLDER',desc:'حامل مسند رأس للسيارة قابل للتمدد للهواتف والأجهزة اللوحية.',price:null,art:'case-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['الرحلات','العائلة'],specs:[['Compatibility','5-inch+ devices'],['Rotation','360°'],['Material','PC+ABS + Aluminum']]},
{id:'rph1003',name:'ROCK RPH1003 Metal Rotatable Desktop Phone Holder',category:'holder',label:'HOLDER',desc:'حامل مكتبي معدني قابل للدوران، ثابت وقابل للطي.',price:null,art:'case-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['المكتب','المنزل'],specs:[['Rotation','360°'],['Material','Carbon Steel + Aluminum'],['Feature','Foldable']]},
{id:'rph0878',name:'ROCK RPH0878 Universal Adjustable Desktop Stand',category:'holder',label:'HOLDER',desc:'ستاند مكتبي قابل للتعديل بزاوية دوران 180° ومضاد للانزلاق.',price:null,art:'case-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['المكتب','المنزل'],specs:[['Rotation','180°'],['Material','Aluminum + PC'],['Feature','Foldable']]},
{id:'w31',name:'ROCK W31 15W Wireless Charger Car Mount',category:'holder',label:'HOLDER + WIRELESS CHARGER',desc:'حامل سيارة بالشحن اللاسلكي 15W وآلية تثبيت تلقائية.',price:null,art:'case-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['السيارة','الشحن'],specs:[['Power','15W'],['Input','5V/2A, 9V/2A'],['Feature','Auto Mechanism']]},
{id:'vacuum-cup',name:'ROCK Vacuum Suction Cup Magnetic Phone Holder',category:'holder',label:'HOLDER',desc:'حامل جوال مغناطيسي بقاعدة شفط قوية ودوران 360° وتعديل ثلاثي المحاور.',price:null,art:'case-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['السيارة','المكتب'],specs:[['Rotation','360°'],['Weight','100g'],['Material','ABS + TPU + Zinc Alloy']]},
{id:'laptop-bag',name:'ROCK Laptop Bag',category:'lifestyle',label:'LIFESTYLE',desc:'حقيبة لابتوب مناسبة حتى 14.9 بوصة مع حماية ثلاثية الطبقات وحزام سفر.',price:null,art:'case-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['اللابتوب','السفر'],specs:[['Compatibility','حتى 14.9″'],['Material','300D Snowflake Fabric'],['Protection','3-Layer Shockproof']]},
{id:'trimmer',name:'ROCK Trimmer Kit',category:'lifestyle',label:'LIFESTYLE',desc:'عدة تشذيب مع مشطين مدمجين وبطارية تشغيل تصل إلى 240 دقيقة.',price:null,art:'case-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['المنزل','السفر'],specs:[['Material','PC'],['Run Time','240 min'],['Features','Two Built-in Combs']]},
{id:'car-aroma',name:'ROCK Car Aroma Diffuser',category:'lifestyle',label:'LIFESTYLE',desc:'معطر سيارة مع تركيبات آمنة وكربون منشط وتغطية عطرية واسعة.',price:null,art:'case-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['السيارة','المنزل'],specs:[['Material','Water + Fragrance + Gel'],['Coverage','360°'],['Size','حوالي 90×30mm']]},
{id:'punk-bag',name:'ROCK Dimensional Punk Storage Bag',category:'lifestyle',label:'LIFESTYLE',desc:'حقيبة تخزين بتصميم Punk ومقاومة للماء مع حزام كتف وشكل متين.',price:null,art:'case-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['السفر','التخزين'],specs:[['Material','PU + Electroplated Hardware'],['Size','250×60×35mm'],['Feature','Water Resistant']]},
{id:'pen',name:'ROCK RST10860 B08 Active Magnetic Capacitance Pen',category:'lifestyle',label:'LIFESTYLE',desc:'قلم لمس مغناطيسي نشط مع سن قابل للاستبدال وعرض طاقة LED.',price:null,art:'case-art',badge:'CATALOG',rating:null,reviews:0,bestFor:['iPad','الرسم والكتابة'],specs:[['Compatibility','iOS 12.2+'],['Nib','Replaceable'],['Display','LED Power Display']]}
];
let activeFilter='all',query='',cart=load('rockCart',[]),wishlist=load('rockWishlist',[]),english=false;
function load(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function save(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
const money=n=>n==null?'السعر عند الطلب':`${n.toLocaleString('ar-SA')} ر.س`;
function ensureCatalogFilters(){const wrap=$('#filterPills');if(!wrap)return;const labels={car:'السيارة',holder:'الحوامل',lifestyle:'Lifestyle'};Object.entries(labels).forEach(([key,label])=>{if(!wrap.querySelector(`[data-filter="${key}"]`)){const b=document.createElement('button');b.dataset.filter=key;b.textContent=label;b.addEventListener('click',()=>setFilter(key));wrap.appendChild(b)}})}
function productList(){let list=products.filter(p=>(activeFilter==='all'||p.category===activeFilter)&&`${p.name} ${p.label} ${p.desc}`.toLowerCase().includes(query.trim().toLowerCase()));if(sort.value==='price-low')list.sort((a,b)=>(a.price??Infinity)-(b.price??Infinity));if(sort.value==='price-high')list.sort((a,b)=>(b.price??-Infinity)-(a.price??-Infinity));if(sort.value==='name')list.sort((a,b)=>a.name.localeCompare(b.name));return list}
function ratingMarkup(p){return p.rating?`<div class="rating">★★★★★ <span>${p.rating} (${p.reviews})</span></div>`:`<div class="rating"><span>بيانات الكتالوج</span></div>`}
function renderProducts(){ensureCatalogFilters();const list=productList();empty.style.display=list.length?'none':'block';grid.innerHTML=list.map(p=>`<article class="product-card reveal visible" data-id="${p.id}" tabindex="0"><div class="product-visual"><span class="product-badge">${p.badge}</span><button class="favorite-btn ${wishlist.includes(p.id)?'active':''}" data-fav="${p.id}" aria-label="${wishlist.includes(p.id)?'إزالة من المفضلة':'إضافة للمفضلة'}">${wishlist.includes(p.id)?'♥':'♡'}</button><div class="product-art ${p.art}"></div></div><div class="product-info"><span class="product-category">${p.label}</span><h3>${p.name}</h3>${ratingMarkup(p)}<p>${p.desc}</p><div class="product-bottom"><strong class="product-price">${money(p.price)}</strong><button class="product-add" data-add="${p.id}" aria-label="إضافة ${p.name}">+</button></div></div></article>`).join('')||'';$$('[data-add]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();addToCart(b.dataset.add)}));$$('[data-fav]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();toggleWish(b.dataset.fav)}));$$('.product-card').forEach(c=>c.addEventListener('click',()=>openProduct(c.dataset.id)));}
function findProduct(id){return products.find(p=>p.id===id)}
function toggleWish(id){wishlist=wishlist.includes(id)?wishlist.filter(x=>x!==id):[...wishlist,id];save('rockWishlist',wishlist);renderProducts()}
function addToCart(id){const p=findProduct(id);if(!p)return;const item=cart.find(x=>x.id===id);if(item)item.qty++;else cart.push({id,qty:1});save('rockCart',cart);renderCart();openCart()}
function changeQty(id,delta){const item=cart.find(x=>x.id===id);if(!item)return;item.qty+=delta;if(item.qty<=0)cart=cart.filter(x=>x.id!==id);save('rockCart',cart);renderCart()}
function renderCart(){if(!cart.length){cartItems.innerHTML='<div class="empty-cart">السلة فارغة<br><span>أضف منتجًا لتبدأ</span></div>';cartCount.textContent='0';cartTotal.textContent='0 ر.س';return}let total=0,priced=false,count=0;cartItems.innerHTML=cart.map(x=>{const p=findProduct(x.id);if(!p)return '';if(p.price!=null){total+=p.price*x.qty;priced=true}count+=x.qty;return `<div class="cart-row"><div><strong>${p.name}</strong><small>${money(p.price)} × ${x.qty}</small></div><div class="qty"><button data-minus="${p.id}">−</button><b>${x.qty}</b><button data-plus="${p.id}">+</button><button class="cart-remove" data-remove="${p.id}">حذف</button></div></div>`}).join('');cartCount.textContent=count;cartTotal.textContent=priced?money(total):'يحدد عند الطلب';$$('[data-minus]').forEach(b=>b.onclick=()=>changeQty(b.dataset.minus,-1));$$('[data-plus]').forEach(b=>b.onclick=()=>changeQty(b.dataset.plus,1));$$('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.id!==b.dataset.remove);save('rockCart',cart);renderCart()})}
function openCart(){cartDrawer.classList.add('open');overlay.classList.add('open');document.body.classList.add('no-scroll')}
function hideCart(){cartDrawer.classList.remove('open');overlay.classList.remove('open');document.body.classList.remove('no-scroll')}
function setFilter(f){activeFilter=f;$$('#filterPills button').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));renderProducts()}
function openProduct(id){const p=findProduct(id),m=$('#productModal');if(!p||!m)return;m.innerHTML=`<div class="product-modal-card"><button class="modal-close" data-close-product>×</button><div class="modal-art product-art ${p.art}"></div><div class="modal-copy"><span class="product-category">${p.label}</span><h2>${p.name}</h2>${ratingMarkup(p)}<p>${p.desc}</p><div class="modal-specs">${p.specs.map(s=>`<div><span>${s[0]}</span><b>${s[1]}</b></div>`).join('')}</div><h4>مناسب لـ</h4><div class="best-for">${p.bestFor.map(x=>`<span>${x}</span>`).join('')}</div><div class="modal-buy"><strong>${money(p.price)}</strong><button class="btn btn-primary" data-modal-add="${p.id}">أضف إلى السلة</button></div></div></div>`;m.classList.add('open');m.querySelector('[data-close-product]').onclick=()=>m.classList.remove('open');m.querySelector('[data-modal-add]').onclick=()=>{addToCart(id);m.classList.remove('open')}}
function openFinder(){const m=$('#finderModal');m.classList.add('open');m.innerHTML=`<div class="finder-card"><button class="modal-close" data-close-finder>×</button><p class="eyebrow">ROCK FINDER</p><h2>ساعدني أختار</h2><p>جاوب بثلاث خطوات ونقترح عليك نقطة بداية مناسبة من كتالوج ROCK.</p><div class="finder-step"><label>جهازك</label><div class="finder-options" data-choice="device"><button data-v="iphone">iPhone</button><button data-v="samsung">Samsung</button><button data-v="ipad">iPad / Mac</button><button data-v="all">أكثر من جهاز</button></div></div><div class="finder-step"><label>استخدامك</label><div class="finder-options" data-choice="use"><button data-v="travel">سفر</button><button data-v="desk">مكتب</button><button data-v="car">سيارة</button><button data-v="daily">يومي</button></div></div><button class="btn btn-primary finder-result" id="finderResult">اعرض ترشيحي</button><div id="finderOutput"></div></div>`;const values={};$$('.finder-options button',m).forEach(b=>b.onclick=()=>{values[b.parentElement.dataset.choice]=b.dataset.v;$$('.finder-options button',b.parentElement).forEach(x=>x.classList.toggle('selected',x===b))});$('#finderResult',m).onclick=()=>{let candidates=[...products];if(values.device==='iphone')candidates=candidates.filter(p=>p.bestFor.includes('iPhone')||p.desc.includes('iPhone')||p.category!=='lifestyle');if(values.use==='travel')candidates=candidates.sort((a,b)=>(b.bestFor.includes('السفر')?1:0)-(a.bestFor.includes('السفر')?1:0));if(values.use==='car')candidates=candidates.sort((a,b)=>(b.category==='car'||b.bestFor.includes('السيارة')?1:0)-(a.category==='car'||a.bestFor.includes('السيارة')?1:0));if(values.use==='desk')candidates=candidates.sort((a,b)=>(b.bestFor.includes('المكتب')?1:0)-(a.bestFor.includes('المكتب')?1:0));const scored=candidates[0]||products[0];$('#finderOutput',m).innerHTML=`<div class="finder-match"><span>ترشيح ROCK</span><strong>${scored.name}</strong><small>${money(scored.price)} · ${scored.desc}</small><button class="btn btn-light" id="finderAdd">أضف إلى السلة</button></div>`;$('#finderAdd',m).onclick=()=>{addToCart(scored.id);m.classList.remove('open')}};$('[data-close-finder]',m).onclick=()=>m.classList.remove('open')}
menuBtn?.addEventListener('click',()=>mobileMenu.classList.toggle('open'));$$('#mobileMenu a').forEach(a=>a.onclick=()=>mobileMenu.classList.remove('open'));cartBtn?.addEventListener('click',openCart);closeCart?.addEventListener('click',hideCart);overlay?.addEventListener('click',hideCart);
$$('.add-demo').forEach(btn=>btn.addEventListener('click',()=>{const p=products.find(x=>x.name===btn.dataset.product)||products.find(x=>x.id===btn.dataset.product);if(p)addToCart(p.id)}));
ensureCatalogFilters();$$('#filterPills button').forEach(btn=>btn.addEventListener('click',()=>setFilter(btn.dataset.filter)));$$('[data-filter-link]').forEach(card=>card.addEventListener('click',()=>setFilter(card.dataset.filterLink)));
search?.addEventListener('input',e=>{query=e.target.value;renderProducts()});sort?.addEventListener('change',renderProducts);$('#filterToggle')?.addEventListener('click',()=>$('#filterPills').classList.toggle('open'));
$('#finderBtn')?.addEventListener('click',openFinder);$('#searchBtn')?.addEventListener('click',()=>{$('#searchOverlay').classList.add('open');$('#overlaySearch').focus()});$('#closeSearch')?.addEventListener('click',()=>$('#searchOverlay').classList.remove('open'));$('#overlaySearch')?.addEventListener('input',e=>{query=e.target.value;search.value=e.target.value;renderProducts()});
window.addEventListener('scroll',()=>nav.classList.toggle('scrolled',window.scrollY>30));
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(el=>observer.observe(el));
window.addEventListener('mousemove',e=>{if(matchMedia('(hover:hover)').matches)$$('.parallax').forEach(el=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-(r.left+r.width/2))*.01}px,${(e.clientY-(r.top+r.height/2))*.007}px)`})});
langBtn?.addEventListener('click',()=>{english=!english;document.documentElement.dir=english?'ltr':'rtl';document.documentElement.lang=english?'en':'ar';langBtn.textContent=english?'AR':'EN';const set=(s,a,b)=>{const el=$(s);if(el)el.textContent=english?b:a};set('.hero h1','تقنية تتحرك معك','Tech that moves with you');set('.hero-text','إكسسوارات جوال تجمع بين الأداء، التصميم والاعتمادية — من أول شحنة إلى آخر لحظة في يومك.','Mobile accessories built around performance, design and reliability — from the first charge to the last moment of your day.')});
$('#checkoutBtn')?.addEventListener('click',()=>{if(!cart.length){openCart();return}const lines=cart.map(x=>{const p=findProduct(x.id);return `${p.name} × ${x.qty} — ${money(p.price)}`}).join('%0A');window.location.href=`mailto:hello@rock.sa?subject=ROCK%20Catalog%20Order&body=${lines}`});
renderProducts();renderCart();