const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const nav=$('#nav'),menuBtn=$('#menuBtn'),mobileMenu=$('#mobileMenu'),cartBtn=$('#cartBtn'),closeCart=$('#closeCart'),cartDrawer=$('#cartDrawer'),overlay=$('#overlay'),cartItems=$('#cartItems'),cartCount=$('#cartCount'),cartTotal=$('#cartTotal'),langBtn=$('#langBtn');
const grid=$('#productGrid'),empty=$('#emptyProducts'),search=$('#productSearch'),sort=$('#sortProducts');
$('#year').textContent=new Date().getFullYear();
const products=[
{id:'gan65',name:'ROCK GaN 65W',category:'power',label:'CHARGER',desc:'شاحن سريع صغير بتقنية GaN للاستخدام اليومي والسفر.',price:129,art:'charger-art',badge:'BEST SELLER',rating:4.8,reviews:124,bestFor:['السفر','المكتب','المنزل'],specs:[['القدرة','65W'],['التقنية','GaN'],['المنافذ','3 Ports']]},
{id:'power20k',name:'ROCK Power 20K',category:'power',label:'POWER BANK',desc:'بطارية متنقلة 20,000mAh مع طاقة تصل إلى 22.5W.',price:149,art:'power-art',badge:'FEATURED',rating:4.9,reviews:186,bestFor:['السفر','الاستخدام الطويل'],specs:[['السعة','20,000mAh'],['القدرة','22.5W'],['المخارج','3']]},
{id:'usbc100',name:'ROCK USB-C 100W',category:'power',label:'CABLE',desc:'كيبل USB-C عالي القدرة للشحن السريع ونقل الطاقة.',price:59,art:'cable-art',badge:'NEW',rating:4.7,reviews:86,bestFor:['اللابتوب','الجوال'],specs:[['القدرة','100W'],['المنفذ','USB-C'],['الاستخدام','Charge + Data']]},
{id:'magsafe',name:'ROCK MagSafe Case',category:'protection',label:'PROTECTION',desc:'حماية خفيفة بتصميم نظيف وتوافق مغناطيسي.',price:89,art:'case-art',badge:'POPULAR',rating:4.7,reviews:93,bestFor:['الاستخدام اليومي','iPhone'],specs:[['التوافق','MagSafe'],['الحماية','يومية'],['التصميم','Slim']]},
{id:'glasspro',name:'ROCK Glass Pro',category:'protection',label:'SCREEN',desc:'حماية شاشة واضحة للاستخدام اليومي مع تركيب سهل.',price:49,art:'case-art',badge:'NEW',rating:4.6,reviews:71,bestFor:['iPhone','Samsung'],specs:[['النوع','Screen Protector'],['وضوح','HD'],['التركيب','Easy']]},
{id:'airbuds',name:'ROCK AirBuds',category:'audio',label:'AUDIO',desc:'سماعات لاسلكية بتصميم مريح وصوت واضح.',price:179,art:'earbuds-art',badge:'BEST SELLER',rating:4.8,reviews:142,bestFor:['التنقل','المكالمات'],specs:[['الاتصال','Wireless'],['الصوت','Stereo'],['الاستخدام','Everyday']]},
{id:'soundmini',name:'ROCK Sound Mini',category:'audio',label:'AUDIO',desc:'سماعة صغيرة للحياة اليومية والتنقل.',price:119,art:'earbuds-art',badge:'POPULAR',rating:4.6,reviews:64,bestFor:['السفر','المكتب'],specs:[['الحجم','Compact'],['الاتصال','Wireless'],['الاستخدام','Portable']]},
{id:'3in1',name:'ROCK 3-in-1 Cable',category:'power',label:'CABLE',desc:'كيبل متعدد الاستخدامات للشحن في أكثر من سيناريو.',price:69,art:'cable-art',badge:'SMART PICK',rating:4.7,reviews:58,bestFor:['السفر','السيارة'],specs:[['التصميم','3-in-1'],['الاستخدام','Multi-device'],['التوافق','Universal']]}
];
let activeFilter='all',query='',cart=load('rockCart',[]),wishlist=load('rockWishlist',[]),english=false;
function load(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function save(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
const money=n=>`${n.toLocaleString('ar-SA')} ر.س`;
function productList(){let list=products.filter(p=>(activeFilter==='all'||p.category===activeFilter)&&`${p.name} ${p.label} ${p.desc}`.toLowerCase().includes(query.trim().toLowerCase()));if(sort.value==='price-low')list.sort((a,b)=>a.price-b.price);if(sort.value==='price-high')list.sort((a,b)=>b.price-a.price);if(sort.value==='name')list.sort((a,b)=>a.name.localeCompare(b.name));return list}
function renderProducts(){const list=productList();empty.style.display=list.length?'none':'block';grid.innerHTML=list.map(p=>`<article class="product-card reveal visible" data-id="${p.id}" tabindex="0"><div class="product-visual"><span class="product-badge">${p.badge}</span><button class="favorite-btn ${wishlist.includes(p.id)?'active':''}" data-fav="${p.id}" aria-label="${wishlist.includes(p.id)?'إزالة من المفضلة':'إضافة للمفضلة'}">${wishlist.includes(p.id)?'♥':'♡'}</button><div class="product-art ${p.art}"></div></div><div class="product-info"><span class="product-category">${p.label}</span><h3>${p.name}</h3><div class="rating">★★★★★ <span>${p.rating} (${p.reviews})</span></div><p>${p.desc}</p><div class="product-bottom"><strong class="product-price">${money(p.price)}</strong><button class="product-add" data-add="${p.id}" aria-label="إضافة ${p.name}">+</button></div></div></article>`).join('')||'';$$('[data-add]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();addToCart(b.dataset.add)}));$$('[data-fav]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();toggleWish(b.dataset.fav)}));$$('.product-card').forEach(c=>c.addEventListener('click',()=>openProduct(c.dataset.id)));}
function findProduct(id){return products.find(p=>p.id===id)}
function toggleWish(id){wishlist=wishlist.includes(id)?wishlist.filter(x=>x!==id):[...wishlist,id];save('rockWishlist',wishlist);renderProducts()}
function addToCart(id){const p=findProduct(id);if(!p)return;const item=cart.find(x=>x.id===id);if(item)item.qty++;else cart.push({id,qty:1});save('rockCart',cart);renderCart();openCart()}
function changeQty(id,delta){const item=cart.find(x=>x.id===id);if(!item)return;item.qty+=delta;if(item.qty<=0)cart=cart.filter(x=>x.id!==id);save('rockCart',cart);renderCart()}
function renderCart(){if(!cart.length){cartItems.innerHTML='<div class="empty-cart">السلة فارغة<br><span>أضف منتجًا لتبدأ</span></div>';cartCount.textContent='0';cartTotal.textContent='0 ر.س';return}let total=0,count=0;cartItems.innerHTML=cart.map(x=>{const p=findProduct(x.id);if(!p)return '';total+=p.price*x.qty;count+=x.qty;return `<div class="cart-row"><div><strong>${p.name}</strong><small>${money(p.price)} × ${x.qty}</small></div><div class="qty"><button data-minus="${p.id}">−</button><b>${x.qty}</b><button data-plus="${p.id}">+</button><button class="cart-remove" data-remove="${p.id}">حذف</button></div></div>`}).join('');cartCount.textContent=count;cartTotal.textContent=money(total);$$('[data-minus]').forEach(b=>b.onclick=()=>changeQty(b.dataset.minus,-1));$$('[data-plus]').forEach(b=>b.onclick=()=>changeQty(b.dataset.plus,1));$$('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.id!==b.dataset.remove);save('rockCart',cart);renderCart()})}
function openCart(){cartDrawer.classList.add('open');overlay.classList.add('open');document.body.classList.add('no-scroll')}
function hideCart(){cartDrawer.classList.remove('open');overlay.classList.remove('open');document.body.classList.remove('no-scroll')}
function setFilter(f){activeFilter=f;$$('#filterPills button').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));renderProducts()}
function openProduct(id){const p=findProduct(id),m=$('#productModal');if(!p||!m)return;m.innerHTML=`<div class="product-modal-card"><button class="modal-close" data-close-product>×</button><div class="modal-art product-art ${p.art}"></div><div class="modal-copy"><span class="product-category">${p.label}</span><h2>${p.name}</h2><div class="rating">★★★★★ <span>${p.rating} / 5 · ${p.reviews} مراجعة</span></div><p>${p.desc}</p><div class="modal-specs">${p.specs.map(s=>`<div><span>${s[0]}</span><b>${s[1]}</b></div>`).join('')}</div><h4>مناسب لـ</h4><div class="best-for">${p.bestFor.map(x=>`<span>${x}</span>`).join('')}</div><div class="modal-buy"><strong>${money(p.price)}</strong><button class="btn btn-primary" data-modal-add="${p.id}">أضف إلى السلة</button></div></div></div>`;m.classList.add('open');m.querySelector('[data-close-product]').onclick=()=>m.classList.remove('open');m.querySelector('[data-modal-add]').onclick=()=>{addToCart(id);m.classList.remove('open')}}
function openFinder(){const m=$('#finderModal');m.classList.add('open');m.innerHTML=`<div class="finder-card"><button class="modal-close" data-close-finder>×</button><p class="eyebrow">ROCK FINDER</p><h2>ساعدني أختار</h2><p>جاوب بثلاث خطوات ونقترح عليك نقطة بداية مناسبة.</p><div class="finder-step"><label>جهازك</label><div class="finder-options" data-choice="device"><button data-v="iphone">iPhone</button><button data-v="samsung">Samsung</button><button data-v="ipad">iPad / Mac</button><button data-v="all">أكثر من جهاز</button></div></div><div class="finder-step"><label>استخدامك</label><div class="finder-options" data-choice="use"><button data-v="travel">سفر</button><button data-v="desk">مكتب</button><button data-v="car">سيارة</button><button data-v="daily">يومي</button></div></div><div class="finder-step"><label>ميزانيتك</label><div class="finder-options" data-choice="budget"><button data-v="under100">أقل من 100</button><button data-v="100200">100–200</button><button data-v="any">مفتوحة</button></div></div><button class="btn btn-primary finder-result" id="finderResult">اعرض ترشيحي</button><div id="finderOutput"></div></div>`;const values={};$$('.finder-options button',m).forEach(b=>b.onclick=()=>{values[b.parentElement.dataset.choice]=b.dataset.v;$$('.finder-options button',b.parentElement).forEach(x=>x.classList.toggle('selected',x===b))});$('#finderResult',m).onclick=()=>{let candidates=[...products];if(values.budget==='under100')candidates=candidates.filter(p=>p.price<100);if(values.budget==='100200')candidates=candidates.filter(p=>p.price>=100&&p.price<=200);if(!candidates.length)candidates=products.filter(p=>p.price<200);let scored=candidates.map(p=>{let s=p.rating*2;if(values.device==='iphone'&&p.category==='protection')s+=2;if(values.use==='travel'&&p.bestFor.includes('السفر'))s+=4;if(values.use==='desk'&&p.bestFor.includes('المكتب'))s+=3;if(values.use==='car'&&p.bestFor.includes('السيارة'))s+=4;if(values.use==='daily'&&p.bestFor.includes('الاستخدام اليومي'))s+=3;return {p,s}}).sort((a,b)=>b.s-a.s)[0];$('#finderOutput',m).innerHTML=`<div class="finder-match"><span>ترشيح ROCK</span><strong>${scored.p.name}</strong><small>${money(scored.p.price)} · ${scored.p.desc}</small><button class="btn btn-light" id="finderAdd">أضف إلى السلة</button></div>`;$('#finderAdd',m).onclick=()=>{addToCart(scored.p.id);m.classList.remove('open')}};$('#finderResult',m).insertAdjacentHTML('afterend','') ;$('[data-close-finder]',m).onclick=()=>m.classList.remove('open')}
menuBtn?.addEventListener('click',()=>mobileMenu.classList.toggle('open'));$$('#mobileMenu a').forEach(a=>a.onclick=()=>mobileMenu.classList.remove('open'));cartBtn?.addEventListener('click',openCart);closeCart?.addEventListener('click',hideCart);overlay?.addEventListener('click',hideCart);
$$('.add-demo').forEach(btn=>btn.addEventListener('click',()=>{const p=products.find(x=>x.name===btn.dataset.product)||products.find(x=>x.id===btn.dataset.product);if(p)addToCart(p.id)}));
$$('#filterPills button').forEach(btn=>btn.addEventListener('click',()=>setFilter(btn.dataset.filter)));$$('[data-filter-link]').forEach(card=>card.addEventListener('click',()=>setFilter(card.dataset.filterLink)));
search?.addEventListener('input',e=>{query=e.target.value;renderProducts()});sort?.addEventListener('change',renderProducts);$('#filterToggle')?.addEventListener('click',()=>$('#filterPills').classList.toggle('open'));
$('#finderBtn')?.addEventListener('click',openFinder);$('#searchBtn')?.addEventListener('click',()=>{$('#searchOverlay').classList.add('open');$('#overlaySearch').focus()});$('#closeSearch')?.addEventListener('click',()=>$('#searchOverlay').classList.remove('open'));$('#overlaySearch')?.addEventListener('input',e=>{query=e.target.value;search.value=e.target.value;renderProducts()});
window.addEventListener('scroll',()=>nav.classList.toggle('scrolled',window.scrollY>30));
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(el=>observer.observe(el));
window.addEventListener('mousemove',e=>{if(matchMedia('(hover:hover)').matches)$$('.parallax').forEach(el=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-(r.left+r.width/2))*.01}px,${(e.clientY-(r.top+r.height/2))*.007}px)`})});
langBtn?.addEventListener('click',()=>{english=!english;document.documentElement.dir=english?'ltr':'rtl';document.documentElement.lang=english?'en':'ar';langBtn.textContent=english?'AR':'EN';const set=(s,a,b)=>{const el=$(s);if(el)el.textContent=english?b:a};set('.hero h1','تقنية تتحرك معك','Tech that moves with you');set('.hero-text','إكسسوارات جوال تجمع بين الأداء، التصميم والاعتمادية — من أول شحنة إلى آخر لحظة في يومك.','Mobile accessories built around performance, design and reliability — from the first charge to the last moment of your day.')});
$('#checkoutBtn')?.addEventListener('click',()=>{if(!cart.length){openCart();return}const lines=cart.map(x=>{const p=findProduct(x.id);return `${p.name} × ${x.qty} — ${money(p.price*x.qty)}`}).join('%0A');window.location.href=`mailto:hello@rock.sa?subject=ROCK%20Order&body=${lines}`});
renderProducts();renderCart();